apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: hknjviwyz-go 
  janus-idp.io/tekton: hknjviwyz-go
  backstage.io/kubernetes-id: hknjviwyz-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: hknjviwyz-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml